import { useEffect, useState } from 'react'
import { CalendarDays, Check, ChevronRight, Clock3, MapPin, PackageCheck, Plus } from 'lucide-react'
import { Link, useSearchParams } from 'react-router-dom'
import { DEMO_TODAY, useDemoStore } from '../../app/store'
import { MiniCalendar } from '../../components/calendar/MiniCalendar'
import { Badge, Button, Card, Modal } from '../../components/ui'
import { formatChecklistDate } from '../checklist/checklistUtils'

const TODAY = DEMO_TODAY
const typeTone: Record<string, 'rose' | 'sage' | 'amber' | 'neutral'> = { 드레스: 'rose', 스튜디오: 'sage', 미팅: 'amber', 메이크업: 'rose', 계약: 'neutral', 본식: 'rose' }
const addDays = (date: string, days: number) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + days); return next.toISOString().slice(0, 10) }

export function DashboardPage() {
  const { couples, events, checklist, orderReminders, vendors, addVendor, addOrderReminder } = useDemoStore()
  const [searchParams, setSearchParams] = useSearchParams()
  const [selectedDate, setSelectedDate] = useState(TODAY)
  const [orderModalOpen, setOrderModalOpen] = useState(searchParams.get('openOrderReminder') === '1')
  const [orderDraft, setOrderDraft] = useState({ coupleId: couples[0]?.id ?? '', vendorId: '', title: '', orderDate: TODAY, reminderDate: addDays(TODAY, 7) })
  const [vendorQuery, setVendorQuery] = useState('')
  const [vendorPickerOpen, setVendorPickerOpen] = useState(false)
  const [scheduleSlide, setScheduleSlide] = useState<'today' | 'upcoming'>('today')
  const [scheduleTouchStart, setScheduleTouchStart] = useState<number | null>(null)
  useEffect(() => { if (searchParams.get('openOrderReminder') === '1') { setOrderModalOpen(true); const next = new URLSearchParams(searchParams); next.delete('openOrderReminder'); setSearchParams(next, { replace: true }) } }, [searchParams, setSearchParams])
  const todayEvents = events.filter((event) => event.date === selectedDate).sort((a, b) => a.time.localeCompare(b.time))
  const todayTasks = checklist.filter((item) => item.status !== 'completed' && item.dueDate === TODAY).sort((a, b) => a.dueDate.localeCompare(b.dueDate))
  const deadlines = checklist.filter((item) => item.status !== 'completed' && item.dueDate >= TODAY).sort((a, b) => a.dueDate.localeCompare(b.dueDate)).slice(0, 6)
  const moveScheduleSlide = (direction: -1 | 1) => setScheduleSlide((current) => direction > 0 ? 'upcoming' : 'today')
  const handleScheduleTouchEnd = (clientX: number) => { if (scheduleTouchStart === null) return; const distance = clientX - scheduleTouchStart; if (Math.abs(distance) >= 45) moveScheduleSlide(distance < 0 ? 1 : -1); setScheduleTouchStart(null) }
  const matchedVendors = vendors.filter((vendor) => `${vendor.name} ${vendor.category} ${vendor.location}`.toLowerCase().includes(vendorQuery.trim().toLowerCase())).slice(0, 6)
  const submitOrderReminder = () => { if (!orderDraft.coupleId || !orderDraft.title.trim()) return; addOrderReminder({ ...orderDraft, vendorId: orderDraft.vendorId || undefined, title: orderDraft.title.trim(), memo: '' }); setOrderDraft({ coupleId: orderDraft.coupleId, vendorId: '', title: '', orderDate: TODAY, reminderDate: addDays(TODAY, 7) }); setVendorQuery(''); setOrderModalOpen(false) }
  const selectVendor = (vendorId: string, name: string) => { setOrderDraft({ ...orderDraft, vendorId }); setVendorQuery(name); setVendorPickerOpen(false) }
  const registerVendor = () => { const name = vendorQuery.trim(); if (!name) return; const base = vendors[0]; const id = addVendor({ name, category: '기타', summary: '플래너가 직접 등록한 업체', tags: [], priceRange: '가격 협의', match: 0, image: base?.image ?? '', location: '지역 미등록', address: '주소 미등록', hours: '운영시간 미등록', phone: '연락처 미등록', instagram: '', activeEvent: '직접 등록', gallery: base?.gallery?.slice(0, 3) ?? [], updatedAt: TODAY }); selectVendor(id, name) }

  return <div className="dashboard-page dashboard-page--focused">
    <header className="dashboard-welcome"><div className="dashboard-welcome__date"><strong>05</strong><span>AUG<br />WED</span></div><div className="dashboard-welcome__copy"><p>2026년 8월 5일 수요일</p><h1>좋은 아침이에요, 이지윤 플래너님.</h1><span>오늘 처리할 흐름을 우선순위대로 정리했습니다.</span></div><div className="dashboard-welcome__counts"><span><i>{events.filter((event) => event.date === TODAY).length}</i> 오늘 일정</span><span><i>{checklist.filter((item) => item.status !== 'completed').length}</i> 준비 업무</span><span><i>{deadlines.length}</i> 예정 업무</span></div></header>
    <section className="dashboard-focus-grid">
      <Card padding="none" className="dashboard-focus dashboard-focus--schedule"><header><div><p className="eyebrow">Monthly overview</p><h2>월별 일정</h2></div><Link to="/calendar">전체 캘린더 <ChevronRight size={14} /></Link></header><div className="dashboard-calendar-content"><MiniCalendar events={events} initialDate={TODAY} onSelect={setSelectedDate} /><div className="dashboard-selected-schedule"><header><strong>오늘의 할 일</strong><span>{todayTasks.length}건</span></header><div className="dashboard-today-list">{todayTasks.length ? todayTasks.map((task) => <Link to={'/couples/' + task.coupleId + '?tab=timeline'} className="dashboard-today-row" key={task.id}><time><Check size={12} /><strong>{formatChecklistDate(task.dueDate).split(" ")[0]}</strong><span>오늘</span></time><div><div><Badge tone="sage">{task.category}</Badge><span>{couples.find((item) => item.id === task.coupleId)?.partners}</span></div><h3>{task.title}</h3><p>{task.owner} 담당</p></div><ChevronRight size={15} /></Link>) : <div className="dashboard-focus-empty"><Check size={20} /><span>오늘 처리할 일이 없습니다.</span></div>}</div></div></div></Card>
      <Card padding="none" className="dashboard-focus dashboard-focus--schedule-carousel"><header><div><p className="eyebrow">Schedule focus</p><h2>{scheduleSlide === 'today' ? '오늘 일정' : '예정 업무'}</h2></div><nav className="dashboard-schedule-pager"><button type="button" className={scheduleSlide === 'today' ? 'active' : ''} onClick={() => setScheduleSlide('today')}>오늘 일정</button><button type="button" className={scheduleSlide === 'upcoming' ? 'active' : ''} onClick={() => setScheduleSlide('upcoming')}>예정 업무</button></nav></header><div className="dashboard-schedule-carousel__viewport" onTouchStart={(event) => setScheduleTouchStart(event.touches[0]?.clientX ?? null)} onTouchEnd={(event) => handleScheduleTouchEnd(event.changedTouches[0]?.clientX ?? 0)}><div className="dashboard-schedule-carousel__track" style={{ transform: `translateX(${scheduleSlide === 'today' ? '0' : '-100'}%)` }}><div className="dashboard-schedule-carousel__slide"><div className="dashboard-today-list">{events.filter((event) => event.date === TODAY).length ? events.filter((event) => event.date === TODAY).sort((a, b) => a.time.localeCompare(b.time)).map((event) => { const couple = couples.find((item) => item.id === event.coupleId); return <Link to="/calendar" className="dashboard-today-row" key={event.id}><time><Clock3 size={12} /><strong>{event.time}</strong><span>{event.endTime}</span></time><div><div><Badge tone={typeTone[event.type] ?? 'neutral'}>{event.type}</Badge><span>{couple?.partners ?? '개인 일정'}</span></div><h3>{event.title}</h3><p><MapPin size={12} /> {event.location}</p></div><ChevronRight size={15} /></Link> }) : <div className="dashboard-focus-empty"><CalendarDays size={20} /><span>오늘 등록된 일정이 없습니다.</span></div>}</div></div><div className="dashboard-schedule-carousel__slide"><div className="dashboard-deadline-list">{deadlines.length ? deadlines.map((task) => <Link to={`/couples/${task.coupleId}?tab=timeline`} key={task.id}><time>{formatChecklistDate(task.dueDate).replace('월 ', '/').replace('일', '')}</time><div><strong>{task.title}</strong><span>{couples.find((item) => item.id === task.coupleId)?.partners} · {task.category}</span></div><ChevronRight size={14} /></Link>) : <div className="dashboard-focus-empty"><span>예정된 업무가 없습니다.</span></div>}</div></div></div></div></Card>
    </section>
    <Modal open={orderModalOpen} onClose={() => setOrderModalOpen(false)} eyebrow="Manual notification" title="발주·확인 알림 추가" footer={<><Button variant="ghost" onClick={() => setOrderModalOpen(false)}>취소</Button><Button icon={<Check size={14} />} disabled={!orderDraft.title.trim()} onClick={submitOrderReminder}>알림 등록</Button></>}><div className="order-reminder-form order-reminder-form--simple"><div className="order-reminder-form__notice"><PackageCheck size={18} /><div><strong>통합 알림에 발주·확인 항목을 추가합니다.</strong><span>원본 업무를 완료 처리하기 전까지 알림에 표시됩니다.</span></div></div><label><span>커플</span><select value={orderDraft.coupleId} onChange={(event) => setOrderDraft({ ...orderDraft, coupleId: event.target.value })}>{couples.map((couple) => <option value={couple.id} key={couple.id}>{couple.partners}</option>)}</select></label><div className="order-vendor-field"><span>업체</span><div className="order-vendor-combobox"><input value={vendorQuery} onFocus={() => setVendorPickerOpen(true)} onChange={(event) => { setVendorQuery(event.target.value); setOrderDraft({ ...orderDraft, vendorId: '' }); setVendorPickerOpen(true) }} placeholder="업체명을 검색하세요" />{vendorPickerOpen && <div className="order-vendor-options">{matchedVendors.map((vendor) => <button type="button" key={vendor.id} onClick={() => selectVendor(vendor.id, vendor.name)}><strong>{vendor.name}</strong><span>{vendor.category} · {vendor.location}</span></button>)}{vendorQuery.trim() && !vendors.some((vendor) => vendor.name.toLowerCase() === vendorQuery.trim().toLowerCase()) && <button type="button" className="order-vendor-register" onClick={registerVendor}><Plus size={14} /><span><strong>‘{vendorQuery.trim()}’ 직접 등록</strong><small>업체 DB에 기타 업체로 추가합니다.</small></span></button>}</div>}</div></div><label className="wide"><span>발주명</span><input value={orderDraft.title} onChange={(event) => setOrderDraft({ ...orderDraft, title: event.target.value })} placeholder="예: 스튜디오 촬영 패키지 발주 확인" /></label><label><span>발주일</span><input type="date" value={orderDraft.orderDate} onChange={(event) => { const orderDate = event.target.value; setOrderDraft({ ...orderDraft, orderDate, reminderDate: addDays(orderDate, 7) }) }} /></label><label><span>확인 예정일</span><input type="date" value={orderDraft.reminderDate} min={orderDraft.orderDate} onChange={(event) => setOrderDraft({ ...orderDraft, reminderDate: event.target.value })} /></label></div></Modal>
  </div>
}