import { useState } from 'react'
import { ArrowLeft, Copy, ExternalLink, Save, Send } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useDemoStore } from '../../app/store'
import { Button, Card } from '../../components/ui'

export function NewCouplePage() {
  const navigate = useNavigate(); const { addCouple, addConsultationCard } = useDemoStore()
  const [partners, setPartners] = useState(''); const [weddingDate, setWeddingDate] = useState('2027-05-01'); const [venue, setVenue] = useState(''); const [budget, setBudget] = useState(''); const [priorities, setPriorities] = useState(''); const [notes, setNotes] = useState(''); const [clientLink, setClientLink] = useState('')
  const generateClientLink = () => setClientLink(`${window.location.origin}/consultation/new-${Date.now()}`)
  const copyLink = async () => { if (!clientLink) return; await navigator.clipboard?.writeText(clientLink) }
  const submit = () => { if (!partners.trim()) return; const id = `c-${Date.now()}`; const names = partners.split('&').map((name) => name.trim()); addCouple({ id, partners, initials: names.map((name) => name.slice(0, 1)).join(' · '), weddingDate, venue: venue || '예식장 미정', progress: 0, status: '준비중', concept: '상담 카드 작성 대기', tone: 'sand' }); addConsultationCard({ coupleId: id, preferredDate: weddingDate, shootDate: '', coupleNames: partners, phone: '', existingVendors: '', studioDirection: '', studioMood: '', dressMood: '', sizes: '', makeupMood: '', budget: budget || '미정', otherPlanner: '', extraPlanning: '', hallDetails: venue, meetingDetails: '', contactPreference: '', priorities: priorities || '미정', notes, source: '플래너 입력' }); navigate(`/couples/${id}`) }
  return <div className="page-stack"><Link className="back-link" to="/couples"><ArrowLeft size={15} /> 커플 관리</Link><section className="page-intro"><div><p className="eyebrow">New couple</p><h1>새 커플 등록</h1><p>기본 정보와 상담 카드를 한 번에 등록하세요.</p></div></section><Card className="new-couple-form"><div className="form-grid"><label className="form-field form-field--wide"><span>커플 이름</span><input value={partners} onChange={(event) => setPartners(event.target.value)} placeholder="예: 김서윤 & 이도현" /></label><label className="form-field"><span>희망 예식일</span><input type="date" value={weddingDate} onChange={(event) => setWeddingDate(event.target.value)} /></label><label className="form-field"><span>예식장</span><input value={venue} onChange={(event) => setVenue(event.target.value)} placeholder="예식장 미정" /></label><label className="form-field"><span>예상 예산</span><input value={budget} onChange={(event) => setBudget(event.target.value)} placeholder="예: 2,000만원" /></label><label className="form-field form-field--wide"><span>우선순위</span><input value={priorities} onChange={(event) => setPriorities(event.target.value)} placeholder="상담에서 가장 중요하게 볼 것" /></label><label className="form-field form-field--wide"><span>상담 메모</span><textarea rows={5} value={notes} onChange={(event) => setNotes(event.target.value)} /></label></div><div className="new-couple-actions"><Button icon={<Save size={15} />} onClick={submit} disabled={!partners.trim()}>커플과 상담 카드 등록</Button><Button variant="secondary" icon={<Send size={15} />} onClick={generateClientLink}>신랑신부가 직접 작성하기</Button></div>{clientLink && <div className="generated-link-box"><div><strong>신랑신부 작성 링크가 생성되었습니다.</strong><span>{clientLink}</span></div><button onClick={copyLink}><Copy size={14} /> 링크 복사</button><a href={clientLink} target="_blank" rel="noreferrer"><ExternalLink size={14} /> 열기</a></div>}</Card></div>
}