import { useState, type FormEvent } from 'react'
import { Plus, Save, X } from 'lucide-react'
import { Badge } from '../../../components/ui'
import type { Contract } from '../../../types'

const contractCategories = ['스튜디오', '드레스', '메이크업', '예물', '예식장']

export function CoupleContractsTab({ initialContracts, coupleId }: { initialContracts: Contract[]; coupleId: string }) {
  const [contractRows, setContractRows] = useState<Contract[]>(initialContracts)
  const [editingContract, setEditingContract] = useState<Contract | null>(null)
  const createEmptyContract = (category = '스튜디오'): Contract => ({ id: '', coupleId, vendorName: '', category, amount: '', payment: '카드', vatIncluded: false, status: '대기', details: '' })
  const saveContract = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    const data = new FormData(event.currentTarget)
    const next: Contract = { id: editingContract?.id || 'ct-' + Date.now(), coupleId, vendorName: String(data.get('vendorName') ?? ''), category: String(data.get('category') ?? '스튜디오'), amount: String(data.get('amount') ?? ''), payment: String(data.get('payment') ?? '카드'), vatIncluded: data.get('vatIncluded') === 'on', status: String(data.get('status') ?? '대기'), details: String(data.get('details') ?? ''), contractDate: String(data.get('contractDate') ?? ''), item: String(data.get('item') ?? ''), contractFile: String(data.get('contractFile') ?? ''), productName: String(data.get('productName') ?? ''), commission: String(data.get('commission') ?? ''), depositDate: String(data.get('depositDate') ?? ''), commissionInfo: String(data.get('commissionInfo') ?? ''), note: String(data.get('note') ?? '') }
    setContractRows((items) => editingContract?.id ? items.map((item) => item.id === editingContract.id ? next : item) : [...items, next])
    setEditingContract(null)
  }

  return (
    <div className="contract-workspace">
      <section className="section-heading"><div><p className="eyebrow">계약 관리</p><h2>계약 상세</h2><p className="muted">분야별 계약 내용을 나누어 확인하고 관리합니다.</p></div><button onClick={() => setEditingContract(createEmptyContract())}><Plus size={15} /> 계약 추가</button></section>
      {contractCategories.map((category) => {
        const rows = contractRows.filter((item) => item.category === category)
        return <section className="contract-category" key={category}><div className="contract-category__heading"><div><p className="eyebrow">{category}</p><h3>{category} 계약</h3></div><button onClick={() => setEditingContract(createEmptyContract(category))}><Plus size={14} /> 등록</button></div><div className="contract-table-wrap"><table className="contract-table"><thead><tr><th>계약일</th><th>품목</th><th>업체명</th><th>계약서</th><th>상품명</th><th>세부 구성</th><th>결제</th><th>VAT</th><th>계약총액</th><th>수수료</th><th>입금일</th><th>상태</th><th>관리</th></tr></thead><tbody>{rows.length ? rows.map((contract) => <tr key={contract.id}><td>{contract.contractDate || '-'}</td><td>{contract.item || '-'}</td><td>{contract.vendorName}</td><td>{contract.contractFile || '-'}</td><td>{contract.productName || '-'}</td><td>{contract.details || '-'}</td><td>{contract.payment}</td><td>{contract.vatIncluded ? 'VAT 포함' : 'VAT 별도'}</td><td>{contract.amount || '-'}</td><td>{contract.commission || '-'}</td><td>{contract.depositDate || '-'}</td><td><Badge tone="sage">{contract.status}</Badge></td><td><div className="contract-row-actions"><button onClick={() => setEditingContract(contract)}>수정</button><button onClick={() => setContractRows((items) => items.filter((item) => item.id !== contract.id))}>삭제</button></div></td></tr>) : <tr><td colSpan={13} className="contract-table__empty">등록된 {category} 계약이 없습니다.</td></tr>}</tbody></table></div><div className="contract-summary"><strong>총 리베이트 금액</strong><span>{rows.reduce((sum, item) => sum + (Number(String(item.commission || '').replace(/[^0-9]/g, '')) || 0), 0).toLocaleString()}원</span><strong>정산 금액</strong><span>0원</span></div></section>
      })}
      {editingContract && <div className="inline-editor contract-editor"><div className="section-heading"><h3>{editingContract.id ? '계약 수정' : '계약 등록'}</h3><button onClick={() => setEditingContract(null)}><X size={15} /></button></div><form onSubmit={saveContract}><div className="contract-editor-grid"><label>구분<select name="category" defaultValue={editingContract.category}>{contractCategories.map((category) => <option value={category} key={category}>{category}</option>)}</select></label><label>품목<input name="item" defaultValue={editingContract.item} placeholder="예: 본식 드레스" /></label><label>계약일<input name="contractDate" type="date" defaultValue={editingContract.contractDate} /></label><label>업체명<input name="vendorName" defaultValue={editingContract.vendorName} required /></label><label>계약서 파일명<input name="contractFile" defaultValue={editingContract.contractFile} placeholder="예: contract-001.pdf" /></label><label>상품명<input name="productName" defaultValue={editingContract.productName} /></label><label>결제수단<select name="payment" defaultValue={editingContract.payment}><option>카드</option><option>계좌이체</option><option>현금</option></select></label><label>VAT<select name="vatIncluded" defaultValue={editingContract.vatIncluded ? 'on' : 'off'}><option value="on">VAT 포함</option><option value="off">VAT 별도</option></select></label><label>계약총액<input name="amount" defaultValue={editingContract.amount} placeholder="예: 3,200,000원" /></label><label>수수료<input name="commission" defaultValue={editingContract.commission} /></label><label>입금일<input name="depositDate" type="date" defaultValue={editingContract.depositDate} /></label><label>상태<select name="status" defaultValue={editingContract.status}><option>대기</option><option>확인 필요</option><option>서명 완료</option><option>결제 완료</option></select></label><label className="contract-editor-grid__wide">세부 구성<textarea name="details" defaultValue={editingContract.details} placeholder="예: 본식 드레스 1벌, 촬영 드레스 3벌, 헬퍼비 별도" /></label><label className="contract-editor-grid__wide">수수료 정보<textarea name="commissionInfo" defaultValue={editingContract.commissionInfo} /></label><label className="contract-editor-grid__wide">비고<textarea name="note" defaultValue={editingContract.note} /></label></div><button className="primary-btn" type="submit"><Save size={15} /> 저장</button></form></div>}
    </div>
  )
}
